# Taps
tap 'homebrew/cask-drivers'
tap 'thoughtbot/formulae'

# The tap-pin command is necessary since mas is already included in the core
# tap of Homebrew. A pinned tap's formulae take precedence over duplicates in
# other taps.
tap 'mas-cli/tap', pin: true

# Casks
cask '1password'
cask 'android-platform-tools'
cask 'arduino'
cask 'arq'
cask 'atom'
cask 'brave-browser'
cask 'coconutbattery'
cask 'cyberduck'
cask 'docker'
cask 'ftdi-vcp-driver'
cask 'gpg-suite'
cask 'iina'
cask 'iterm2'
cask 'kap'
cask 'keepingyouawake'
cask 'ledger-live'
cask 'postico'
cask 'prolific-pl2303'
cask 'qlmarkdown'
cask 'qlstephen'
cask 'silicon-labs-vcp-driver'
cask 'skitch'
cask 'slack'
cask 'spotify'
cask 'sublime-text'
cask 'the-unarchiver'
cask 'transmission'
cask 'viscosity'
cask 'wch-ch34x-usb-serial-driver'
cask 'whatsapp'
cask 'yubico-yubikey-manager'
cask 'zoomus'

# Packages
brew 'aws-google-auth'
brew 'awscli'
brew 'diff-so-fancy'
brew 'docker-credential-helper-ecr'
brew 'git'
brew 'go'
brew 'grc'
brew 'hugo'
brew 'jq'
brew 'mas'
brew 'n'
brew 'platformio'
brew 'postgresql'
brew 'python'
brew 'rcm'
brew 'telnet'
brew 'tldr'
brew 'trash'
brew 'yubico-piv-tool'

# Mac App Store
mas "Apple Configurator 2", id: 1037126344
mas "HEIC Converter", id: 1294126402
mas "Reeder 3", id: 880001334
mas "WiFi Explorer Lite", id: 1408727408
mas "Xcode", id: 497799835
