#!/bin/bash -e

# Install brew dependencies.
install_brew() {
  echo "Running brew..."
  brew bundle --file=brew/Brewfile
}

# Install zplugin.
install_zplugin() {
  if [ "$(command -v zplugin)" ]; then
    echo "Skipping zplugin installation..."
    return 0;
  fi

  echo "Installing zplugin..."

  # Install zplugin.
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma/zplugin/master/doc/install.sh)"
}

# Add vim Vundle.
configure_vim() {
  if [ -e $HOME/.vim/bundle/Vundle.vim ]; then
    echo "Skipping vim vundle..."
    return 0;
  fi

  echo "Installing vim vundle..."
  git clone https://github.com/gmarik/Vundle.vim.git "$HOME/.vim/bundle/Vundle.vim"
  vim -u $HOME/.vimrc.bundles +PluginUpdate +qa
}

# Setup rc files.
symlink_dotfiles() {
  echo "Symlinking dotfiles..."
  rcup -fvd packages | nl -bn
}

# Install latest node.js.
install_nodejs() {
  if [ ! -x "$(which n 2> /dev/null)" ]; then
    return 1;
  fi

  echo "Installing latest node.js..."
  sudo mkdir -p /usr/local/n
  sudo chown -R $(whoami) /usr/local/n
  sudo chown -R $(whoami) /usr/local/bin /usr/local/lib /usr/local/include /usr/local/share
  n latest
}

# Configure duti default file handlers.
configure_duti() {
  echo "Applying duti defaults..."

  # VS Code
  local vsCodeExtensions=(json md py sh yaml yml)
  for extension in "${vsCodeExtensions[@]}"
  do
    duti -s com.microsoft.VSCode .${extension} all
  done

  # The Unarchiver
  local unarchiverExtensions=(zip rar)
  for extension in "${unarchiverExtensions[@]}"
  do
    duti -s com.macpaw.site.theunarchiver .${extension} all
  done
}

# Sublime Text 3.
configure_sublime() {
  if [ -e ~/Library/Application\ Support/Sublime\ Text\ 3/Installed\ Packages/Package\ Control.sublime-package ]; then
    echo "Skipping Sublime defaults..."
    return 0;
  fi

  echo "Applying Sublime defaults..."
  mkdir -p ~/Library/Application\ Support/Sublime\ Text\ 3/Installed\ Packages/
  curl https://packagecontrol.io/Package%20Control.sublime-package -o ~/Library/Application\ Support/Sublime\ Text\ 3/Installed\ Packages/Package\ Control.sublime-package
  rm -rf ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User
  ln -sfv $(pwd)/User ~/Library/Application\ Support/Sublime\ Text\ 3/Packages
}

# Configure iTerm defaults.
configure_iterm() {
  if [ -e ~/Library/Application\ Support/iTerm2/DynamicProfiles ]; then
    echo "Skipping iTerm defaults..."
    return 0;
  fi

  echo "Applying iTerm defaults..."
  mkdir -p ~/Library/Application\ Support/iTerm2/DynamicProfiles
  ln -sfv $(pwd)/library/iterm/profiles/default.json ~/Library/Application\ Support/iTerm2/DynamicProfiles
  source library/iterm/defaults
}

# Configure macOS defaults.
configure_macos() {
  echo "Applying macOS defaults..."
  source macos/defaults
}

install_brew
install_zplugin
symlink_dotfiles
install_nodejs
configure_duti
configure_vim
configure_sublime
configure_iterm
configure_macos
